insert into public.equivallences (id, possibilite, reference)
values  (3, '>', '>'),
        (4, 'plus de', '>'),
        (7, '<', '<'),
        (8, 'moins de', '<'),
        (9, 'egale a', '='),
        (10, 'égal à', '='),
        (11, 'egal a', '='),
        (1, 'superieur a', '>'),
        (2, 'supérieur à', '>'),
        (6, 'inférieur à', '<'),
        (5, 'inferieur a', '<'),
        (12, 'egal à', '='),
        (13, 'meilleur prix', 'ASC'),
        (14, 'le plus bas', 'ASC'),
        (15, 'prix avantageux', 'ASC'),
        (16, 'pire qualite', 'ASC'),
        (17, 'meilleur rapport', 'ASC'),
        (18, 'meilleur ratio', 'ASC'),
        (19, 'bon prix', 'ASC'),
        (20, 'meilleur qualite', 'DESC'),
        (21, 'le plus eleve', 'DESC'),
        (22, 'pire prix', 'DESC'),
        (23, 'pire rapport', 'DESC'),
        (24, 'pire qualite', 'DESC'),
        (25, 'le plus élevé', 'DESC'),
        (27, 'rapport', '/'),
        (26, 'ratio ', 'rapport'),
        (28, 'pire ratio', 'DESC'),
        (31, 'prix le moins cher', 'ASC'),
        (30, 'prix le plus cher', 'DESC');